package com.extractpdf4j;
import com.extractpdf4j.parsers.HybridParser;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
/**
 * SmokeTest: Part of the ExtractPDF4J toolchain.
 *
 * <p>This class is in package <code>com.extractpdf4j</code> and participates in the PDF table
 * extraction pipeline (stream, lattice, and OCR-assisted/hybrid modes). This documentation
 * was autogenerated without modifying program logic.</p>
 *
 * <p>See the project README for architecture and usage details.</p>
 *
 * @author Mehuli Mukherjee
 * @since 2025
 */

public class SmokeTest {
    @Test void api(){ assertNotNull(new HybridParser("sample.pdf").pages("all")); }
}
